FROM ubuntu:16.04

RUN apt-get update; apt-get install -y \

COPY requirements.txt /
RUN find . -name requirements.txt -type f -exec pip install -r {} \;


RUN freshclam

VOLUME /var/lib/clamav

COPY $NAME.$EXTENSION /

ENTRYPOINT ["/$NAME.$EXTENSION"]
CMD [""]
